### ISSUE TITLE
assert missing

### ISSUE THREAD

**Issue by UndefinedIdentifier** [matt77hias/VYGE#2]
program running exception, could you upload assert folder, thanks!
![image](https://user-images.githubusercontent.com/9676660/103155633-8a15e500-47dc-11eb-8805-999e1e5cdc59.png)

**Comment by matt77hias** [comment]
Sorry that violates copyright laws.

**Comment by UndefinedIdentifier** [comment]
https://github.com/ericrrichards/fps/tree/master/FPS/Source/Chapter%2013/Game/Assets
